### PR TITLE
added file lock program

### PR DESCRIPTION
**Pull request by Mr-Wallet**
`lock-myfile.txt-program.exe` will open-for-write `myfile.txt` in the same directory, and not close it. Leave the exe open to test things with a file locked by an outside process.

### CODE REVIEW

**Comment by Mr-Wallet** [comment]
YOU CAN'T LEAVE MY PRs UNMERGED!! YOU WILL REGRET THIS!!!

**Comment by cbargren** [comment]
lol, I was deleting branches yesterday and apparently it automatically rejects PRs for branches that get deleted. :)

**Comment by cbargren** [comment]
btw, nice change, that's super helpful :+1:

**Comment by cbargren** [comment]
Also, is that Sim City? Speaking of blasts from the past... :)

**Pull request merged**
